### ISSUE TITLE
Rebound mechanism for temporary problems

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/jdbc-component#14]
When trying to run a query to INSERT/UPDATE data in a database user may get an error about unexpected termination due to locked resource, like this:
`com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 69) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.`
It is not the only issue. The list of cases with possible solution way can be extended with other error types.

There will be great to have additional option (checkbox) to perform retries based on rebound mechanism to avoid termination of flow's processing.

For example,
To add checkbox `Retry on error, if possible` to step's configuration. The logic should perform limited number of request's retries (for example 3) in case of errors that can be theoretically solved by retry within a short time.

**Comment by A3a3e1** [comment]
The task includes a rebound mechanism for 4 DB types (which varies for them) including deadlock simulation for all DBs and full testing.
