### ISSUE TITLE
Incorrect parsing variables (without surrounding spaces)

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/jdbc-component#16]
There will be an exception, if no space before/after `@variable:type`.
For example, such expression:
`SELECT * FROM films WHERE @watched:boolean= watched AND created = @created:date AND (name=@name)`
There are problems with:
`@watched:boolean= watched`
and
`(name=@name)`

**Comment by shulkaolka** [comment]
**DoD**

**Component development prerequisites:**

- [x] Development team has all needed requirements
- [x] Access to the needed service with all needed permissions is granted
- [x] No open tasks that could block Component development process
- [x] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created
- [x] Component architecture should be discussed and approved before start coding
- [x] New component GIT repo preconditions:
  - repo type (private/public)
  - license type
- [x] Component deployment preconditions:
  - Where to deploy (app.elastic.io etc..)
  - Component's access level on each installation that component must be deployed on

**Development:**

- [x] Code is written and formatted in accordance with the Styling guide
- [x] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [x] Component logs do not contain any sensitive data (credentials, input/output requests, Environment variables)
- [ ] Code is covered with unit tests
- [ ] Component code is covered with integration tests (optional)
- [ ] Triggers/actions comply with OIH patterns
- [ ] Documentation (README.md file in the Github) is 100% ready
- [ ] Changelogs (CHANGELOG.md) are created/updated
- [ ] Component's version is updated in package.json according to Semantic Versioning 2.0.0
- [ ] CI is set up
- [ ] All development branches are reviewed

**After QA:**

- [ ] All development branches are merged into master branch
- [ ] Sprint review preparation is finished (demo flow is built)

**QA:**

- [ ] Test cases for the component are ready at the TestRail
- [ ] Functional testing is finished
- [ ] Regression testing is finished (optional)
- [ ] Component is deployed to the production stage (app.elastic.io) and/or other required stage
  - Component has a proper access level
  - Required Environment Variables are set
  - Smoke test is finished
- [ ] Release notes are done
- [ ] Component Roadmap is updated
- [ ] Component spreadsheet is updated
