### ISSUE TITLE
Incorrect Required Fields

### ISSUE THREAD

**Issue by benburch** [elasticio/jdbc-component#23]
JDBC MSSQL Issue:

Trying to insert into a table the UI suggests that this is a required field, however this is incorrect. 

The column definition is
decimal(15,0) NOT NULL IDENTITY PRIMARY KEY NONCLUSTERED

IDENTITY means it is auto-incrementing and so it is NOT a required field.

<img width="765" alt="Screenshot 2019-07-15 14 28 15" src="https://user-images.githubusercontent.com/6196181/61220729-d4052b00-a70e-11e9-9b7d-c284ca17d5a8.png">

**Comment by shulkaolka** [comment]
@benburch 
> Trying to insert into a table

did you mean `UPSERT BY PRIMARY KEY` action?
According to [documentation](https://github.com/elasticio/jdbc-component):

> UPSERT BY PRIMARY KEY - this action will execute select command from specified table, as search criteria can be used only PRIMARY KEY, and execute insert command by PRIMARY KEY with specified field, if result does not found, else - action will execute update command by PRIMARY KEY with specified field. The action returns only one result row (a primary key is unique).

So despite on `auto-incrementing` property primary key always should be required.
Question is: should we create a new issue for implementing new action like `Upsert by selected field` or you can proceed to use this action according to current implementation?

**Comment by benburch** [comment]
When the table is auto-incrementing you can't insert into that column - the DB rejects the insert.

In this case I just want to INSERT into the table, I can't.. not an UPSERT a plain old INSERT.

**Comment by shulkaolka** [comment]
@benburch new action `Insert` now is present on app.elastic.io, you can try this one.

**Comment by shulkaolka** [comment]
**DoD**

**Component development prerequisites:**

- [x] Development team has all needed requirements
- [x] Access to the needed service with all needed permissions is granted
- [x] No open tasks that could block Component development process
- [x] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created
- [x] Component architecture should be discussed and approved before start coding

**Development:**

- [x] Code is written and formatted in accordance with the Styling guide
- [x] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [x] Component logs does not contain any sensitive data (credentials, input/output requests, Environment variables)
- [x] Code is covered with unit tests
- [x] Component code is covered with integration tests (optional)
- [x] Triggers/actions comply with OIH patterns
- [x] Documentation (README.md file in the Github) is 100% ready
- [x] Changelogs (CHANGELOG.md) are created/updated
- [ ] package.json or build.gradle is updated:
  - Component's version is updated according to Semantic Versioning 2.0.0
  - Component should be dockerised, add: "buildType":"docker"
- [x] CI is set up
- [x] All development branches are reviewed

**After QA:**

- [x] All development branches are merged into master branch
- [x] Sprint review preparation is finished (demo flow is built)

**QA:**

- [ ] Test cases for the component are ready at the TestRail
- [ ] Functional testing is finished
- [ ] Regression testing is finished (optional)
- [ ] Component is deployed to the production stage (app.elastic.io) and/or other required stage
  - Component has a proper access level
  - Required Environment Variables are set
  - Smoke test is finished
- [ ] Release notes is done
- [ ] Component Roadmap is updated
- [ ] Component spreadsheet is updated
