### ISSUE TITLE
Additional configuration parameters

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/jdbc-component#29]
There is requirement to add field for configuration of the connection. It'll be helpful as a solution for fix issues with connection to MySQL 5.7.8+
Also, it could help in solving issues with different encoding types.

For example, there is a list of possible configuration parameters below:
https://jdbc.postgresql.org/documentation/head/connect.html
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html
https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-2017
https://docs.oracle.com/cd/E13222_01/wls/docs81/jdbc_drivers/oracle.html

The next configuration string performs a proper connection to MySQL 5.7.10:
`jdbc:mysql//localhost:3306/testdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC`

**Comment by shulkaolka** [comment]
**DoD**

**Component development prerequisites:**

- [x] Development team has all needed requirements
- [x] Access to the needed service with all needed permissions is granted
- [x] No open tasks that could block Component development process
- [x] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created
- [x] Component architecture should be discussed and approved before start coding

**Development:**

- [x] Code is written and formatted in accordance with the Styling guide
- [x] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [x] Component logs does not contain any sensitive data (credentials, input/output requests, Environment variables)
- [x] Code is covered with unit tests
- [x] Component code is covered with integration tests (optional)
- [ ] Triggers/actions comply with OIH patterns
- [x] Documentation (README.md file in the Github) is 100% ready
- [x] Changelogs (CHANGELOG.md) are created/updated
- [x] Component's version is updated in package.json according to Semantic Versioning 2.0.0
- [x] CI is set up
- [ ] All development branches are reviewed

**After QA:**

- [ ] All development branches are merged into master branch
- [ ] Sprint review preparation is finished (demo flow is built)

**QA:**

- [ ] Test cases for the component are ready at the TestRail
- [ ] Functional testing is finished
- [ ] Regression testing is finished (optional)
- [ ] Component is deployed to the production stage (app.elastic.io) and/or other required stage
  - Component has a proper access level
  - Required Environment Variables are set
  - Smoke test is finished
- [ ] Release notes is done
- [ ] Component Roadmap is updated
- [ ] Component spreadsheet is updated
