### ISSUE TITLE
issue with credentials verification

### ISSUE THREAD

**Issue by vdidushko** [elasticio/jdbc-component#47]
If you have a platform account with special characters used in the e-mail address, it seems like this will not allow you to verify proper credentials.

`INFO  i.e.s.Service T: - Sending response

INFO  i.e.j.JdbcCredentialsVerifier T: - Successfully connected to database. Credentials verified.

INFO  i.e.j.JdbcCredentialsVerifier T: - Closing database connection

INFO  i.e.s.i.HttpUtils T: - Successfully posted json 45 bytes length

INFO  i.e.s.i.HttpUtils T: - Sending POST request to https://e+mail%40mail.com:*****-*******-******

INFO  i.e.s.i.HttpUtils T: - Got 401 response

java.lang.RuntimeException: java.lang.RuntimeException: Got 401 response

at io.elastic.sailor.impl.HttpUtils.sendHttpRequest(HttpUtils.java:105)

at io.elastic.sailor.Service.createResponseAndSend(Service.java:95)

Caused by: java.lang.RuntimeException: Got 401 response`

**Comment by HannaTrotsenko** [comment]
Issue moved to [elasticio/elasticio #3035](https://github.com/elasticio/elasticio/issues/3035) via [**ZenHub**](https://www.zenhub.com/)
